name: C++ Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install lcov
        run: |
          sudo apt install libperlio-gzip-perl libjson-perl
          wget "https://github.com/linux-test-project/lcov/archive/master.zip"
          unzip "master.zip"
          cd "lcov-master"
          sudo make install
          cd ..
          rm -r lcov-master master.zip

      - name: Create Build Environment
        run: mkdir build

      - name: Configure CMake
        run: |
          cd build
          cmake .. -DBUILD_TEST=ON -DCODE_COVERAGE=ON

      - name: Build
        run: |
          cd build
          make

      - name: Test
        run: |
          cd build
          ./run-test

      - name: Report Code Coverage
        run: |
          cd build
          lcov --directory . --capture --output-file coverage.info
          lcov --extract coverage.info "**/CFB/include/**" --output-file coverage.info
          lcov --list coverage.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/coverage.info
          fail_ci_if_error: true
